[options]
; Servidor
http_port = 8070
addons_path = /home/justin/Documentos/odoo19/addons,/home/justin/Documentos/Tesis

; Base de datos
db_host = /var/run/postgresql
db_port = 5432
db_user = justin
db_password =
db_name = tesis_odoo19


log_level = info

; Rendimiento
workers = 0
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
